name: "Build & Test Package"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup Swift Environment
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.3"
      - name: Get Swift Version
        run: swift --version
      - name: Build Package
        run: swift build
      - name: Test Package
        run: swift test
